# Generated by Django 6.0.2 on 2026-02-18 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategori Adı')),
                ('icon', models.CharField(default='bi-tag-fill', max_length=50, verbose_name='İkon Sınıfı (Bootstrap Icon)')),
                ('color', models.CharField(default='bg-secondary', max_length=50, verbose_name='Renk Sınıfı (Bootstrap color)')),
                ('is_bill', models.BooleanField(default=False, verbose_name='Fatura mı?')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Gelir'), ('expense', 'Gider')], max_length=10, verbose_name='Tür')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Son Ödeme Tarihi')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi mi?')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulator.category', verbose_name='Kategori')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
