# Generated by Django 6.0.2 on 2026-02-23 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'İşlem', 'verbose_name_plural': 'İşlemler'},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='simulator.category', verbose_name='Üst Kategori'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Tekrarlayan mı?'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_period',
            field=models.CharField(choices=[('none', 'Tekrar Yok'), ('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık'), ('yearly', 'Yıllık')], default='none', max_length=10, verbose_name='Tekrar Periyodu'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#6366f1', max_length=50, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi-tag-fill', max_length=50, verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Gelir'), ('expense', 'Gider'), ('transfer', 'Transfer')], max_length=10, verbose_name='Tür'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hesap Adı')),
                ('account_type', models.CharField(choices=[('bank', 'Banka Hesabı'), ('credit_card', 'Kredi Kartı'), ('cash', 'Nakit'), ('investment', 'Yatırım')], default='cash', max_length=20, verbose_name='Hesap Türü')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bakiye')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Renk')),
                ('icon', models.CharField(default='bi-wallet2', max_length=50, verbose_name='İkon')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kredi Limiti')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hesap',
                'verbose_name_plural': 'Hesaplar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='simulator.account', verbose_name='Hesap'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etiket',
                'verbose_name_plural': 'Etiketler',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='simulator.tag', verbose_name='Etiketler'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bütçe Limiti')),
                ('month', models.IntegerField(verbose_name='Ay')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.category', verbose_name='Kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bütçe',
                'verbose_name_plural': 'Bütçeler',
                'unique_together': {('user', 'category', 'month', 'year')},
            },
        ),
    ]
